# Generated by Django 3.1.7 on 2021-06-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('Song_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
