# Generated by Django 3.1.7 on 2021-06-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='Song_id',
            new_name='song_id',
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='songs',
            field=models.FileField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='song',
            name='tags',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
