# Generated by Django 3.1.7 on 2021-06-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20210603_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='thumbnail',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
