# Generated by Django 3.1.7 on 2021-06-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20210603_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='music/media'),
        ),
    ]
