# Generated by Django 3.1.7 on 2021-06-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20210604_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendings',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='trendings',
            name='songs',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
