# Generated by Django 3.1.7 on 2021-06-04 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20210605_0135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trendings',
        ),
    ]
